CREATE TABLE USUARIO(ID_USUARIO BIGINT NOT NULL PRIMARY KEY,
DT_CRIACAO TIMESTAMP,
LOGIN VARCHAR(20),
SENHA VARCHAR(20),
STATUS VARCHAR(1),
TIPO VARCHAR(1),
PESSOA_ID_PESSOA BIGINT,
CONSTRAINT FKDRV5JACR0JTOCUE1SCULSVWVS FOREIGN KEY(PESSOA_ID_PESSOA) 
REFERENCES PUBLIC.PESSOA(ID_PESSOA))
